sudo: required
services:
  - docker

before_install:
  - docker build -t jevgenijkersov/rect-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jevgenijkersov/rect-test npm test -- --coverage

after_success:
  - docker build -t jevgenijkersov/multi-client ./client
  - docker build -t jevgenijkersov/multi-nginx ./nginx
  - docker build -t jevgenijkersov/multi-server ./server
  - docker build -t jevgenijkersov/multi-worker ./worker
# Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# take all images & push tme to docker hub
  - docker push jevgenijkersov/multi-client
  - docker push jevgenijkersov/multi-nginx
  - docker push jevgenijkersov/multi-server
  - docker push jevgenijkersov/multi-worker 
