sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t jevgenijkersov/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jevgenijkersov/react-test npm test -- --coverage

after_success:
  - docker build -t jevgenijkersov/multi-client ./client
  - docker build -t jevgenijkersov/multi-nginx ./nginx
  - docker build -t jevgenijkersov/multi-server ./server
  - docker build -t jevgenijkersov/multi-worker ./worker
# Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Take all images & push them to Docker Hub
  - docker push jevgenijkersov/multi-client
  - docker push jevgenijkersov/multi-nginx
  - docker push jevgenijkersov/multi-server
  - docker push jevgenijkersov/multi-worker

deploy:
    provider: elasticbeanstalk
    region: eu-west-1
    app: multi-docker
    env: MultiDocker-env
    bucket_name: <bucket_name>
    bucket_path: docker-multi
    on:
      branch: master
    access_key_id:
        secure: $AWS_ACCESS_KEY
    secret_access_key:
        secure: $AWS_SECRET_KEY